import Head from 'next/head';
import styled from 'styled-components';

const MainWrapper = styled.main`
  font-family: Klarheit Grotesk;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>KolorBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainWrapper>
        <h1>KolorBook</h1>
      </MainWrapper>
    </div>
  );
}
