export { default as ArtOne } from './ArtOne'
export { default as ArtTwo } from './ArtTwo'
export { default as ColorPallette } from './ColorPallette'
export { default as Logo } from './Logo'
export { default as Photo } from './Photo'